include:
  - board: nice_nano_v2
    shield: kyria_rev3_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: kyria_rev3_right nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: settings_reset
